#!/bin/sh
set -e

ARCH="${1:-${ZURVAN_ARCH:-amd64}}"

lb config noauto \
    --distribution trixie \
    --architecture "${ARCH}" \
    --archive-areas "main contrib non-free non-free-firmware" \
    --archive-areas-binary "main contrib non-free non-free-firmware" \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --binary-images iso-hybrid \
    --debian-installer none \
    --mirror-bootstrap        "https://deb.debian.org/debian" \
    --mirror-binary           "https://deb.debian.org/debian" \
    --mirror-chroot-security  "https://deb.debian.org/debian-security" \
    --mirror-binary-security  "https://deb.debian.org/debian-security" \
    --parent-mirror-bootstrap "https://deb.debian.org/debian" \
    --parent-mirror-binary    "https://deb.debian.org/debian" \
    --parent-mirror-chroot-security "https://deb.debian.org/debian-security" \
    --parent-mirror-binary-security "https://deb.debian.org/debian-security" \
    --iso-application "Zurvan Linux" \
    --iso-publisher   "Zurvan Linux - https://zurvanlinux.org" \
    --iso-preparer    "Zurvan Linux live-build pipeline (iso-builder)" \
    --iso-volume      "ZURVAN_LIVE" \
    "${@}"

