modules-search: [ "$(qt5importpath)", "$(libdir)/calamares/modules" ]

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - unpack
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - removeuser
    - packages
    - finished
  - show:
    - finished

branding: zurvan
prompt-install: true
dont-rsync-netmodules: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false
